Refactor Customer Class
albiosz/DeCafe pull request #3
Opened 2024-11-09 16:42 UTC by NilsPetsch1999

added 2 functions because of repeating lines (playaudio, updateSmiley) + simplified a few functions

2024-11-09 19:54 UTC, Mu2menM commented on src/main/java/com/example/decafe/Customer.java
> +    public String getRandomOrder() {
Can you please use here the CafeAssets for the strings : CafeAssets.CAKE.getName() and CafeAssets.COFFEE.getName()

2024-11-09 19:58 UTC, Mu2menM commented on src/main/java/com/example/decafe/Customer.java
>      // Method used to create an Image Object
Remove this function and make the customer class using the single responsibility method in ImageUtil : ImageUtil.getImageFromResources(filename)

2024-11-09 20:03 UTC, Mu2menM commented on src/main/java/com/example/decafe/Customer.java
> +        try {
Add the used image names to ImageAssets and call them from the ImageAssets enum : ImageAssets.SMILEY_GREEN.getName()

2024-11-10 23:02 UTC, albiosz requested changes
Some suggestions that would improve readability from my perspective. I really like the topic of clean code, so I'm always happy to discuss about it ;)

2024-11-10 23:02 UTC, albiosz commented on src/main/java/com/example/decafe/Customer.java
> +        return (order = new Random().nextBoolean() ? "cake" : "coffee");
Why not just?:
```java
return new Random().nextBoolean() ? "cake" : "coffee"
```

2024-11-10 23:02 UTC, albiosz commented on src/main/java/com/example/decafe/Customer.java
> +        return new ImageView();
Now it looks reasonable :+1:

2024-11-10 23:02 UTC, albiosz commented on src/main/java/com/example/decafe/Customer.java
> +            Customer customer = new Customer(customerImage, getLabel(customerImage), freeSeatChosen, getImage(customerImage, smileyImages), getImage(customerImage, coinImages));
From my perspective putting the four lines into one made the code less readable. We also lost the information about what exactly the customer receives (order, smiley, coin).

The article is about Python, but I think the practice is universal:
https://www.linkedin.com/pulse/zen-python-sparse-better-than-dense-paritosh-sharma-ghimire-bez5e/

2024-11-10 23:02 UTC, albiosz commented on src/main/java/com/example/decafe/Customer.java
> +            String imageName = seconds == 59 ? "smileygreen.png" : seconds == 30 ? "smileyyellow.png" : "smileyred.png";
From my perspective, nested ternary operators decrease readability of the code, make it more dense.

https://www.sonarsource.com/blog/stop-nesting-ternaries-javascript/

2024-11-10 23:02 UTC, albiosz commented on src/main/java/com/example/decafe/Customer.java
> +        }
It's nice that `smiley.setVisible(true)` is not repeated, but the numbers: 59, 30, 15 are now, so I do not think it's a big improvement, is it?

2024-11-10 23:02 UTC, albiosz commented on src/main/java/com/example/decafe/Customer.java
> +        playAudio(leftUnhappy ? "wrongChoice.mp3" : "rightChoice.mp3");
That's a nice improvement!

2024-11-11 19:00 UTC, NilsPetsch1999 commented
Made a few changes after looking through your recommendations :) pls review again @albiosz 
integrated CafeAssets, ImageAssets and ImageUtil to Customer Class. tried to implement readability recommendations

2024-11-12 12:07 UTC, albiosz commented on src/main/java/com/example/decafe/Customer.java
> +        }
I had no idea, how to refactor it better, but I got a nice suggestion from ChatGPT ;)
```java
public void waitingTime() {
    TimerTask timerTask = new TimerTask() {
        int seconds = 60;

        @Override
        public void run() {
            seconds--;
            if (seconds == 0) {
                startTimerLeave(Customer.this);
            } else {
                updateSmiley(seconds);
            }
        }
    };
    sixtySecondsTimer.schedule(timerTask, 0, 1000);
}

private void updateSmiley(int seconds) {
    try {
        String imageName = getImageName(seconds);
        CustomerMode mood = getCustomerMode(seconds);
        if (imageName != null && mood != null) {
            setMood(mood);
            smiley.setVisible(true);
            smiley.setImage(ImageUtil.getImageFromResources(imageName));
        }
    } catch (ImageNotFoundException e) {
        e.printStackTrace();
    }
}

private String getImageName(int seconds) {
    switch (seconds) {
        case 59:
            return ImageAssets.CUSTOMER_SMILEY_GREEN.getImage();
        case 30:
            return ImageAssets.CUSTOMER_SMILEY_YELLOW.getImage();
        case 15:
            return ImageAssets.CUSTOMER_SMILEY_RED.getImage();
        default:
            return null;
    }
}

private CustomerMode getCustomerMode(int seconds) {
    switch (seconds) {
        case 59:
            return CustomerMode.GREEN;
        case 30:
            return CustomerMode.YELLOW;
        case 15:
            return CustomerMode.RED;
        default:
            return null;
    }
}
```

2024-11-12 12:10 UTC, albiosz approved these changes
Just added a suggestion, how `waitingTime()` and `updateSmiley()` could be refactored, but it does not need to be applied. Apart from it, it can be merged :+1:

2024-11-12 20:57 UTC, merged